### ISSUE TITLE
Training Issue

### ISSUE THREAD

**Issue by ztrbq** [dianzl/SODFormer#1]
Hi, thanks for your brilliant work.

I came across this error when training with 4 3090gpus:
`
RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling backward the first time.
`

I tried to set `losses.backward(retain_graph=True)` in engine.py, but I got another error:
`RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [256]] is at version 3; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!`

Since there's no multiple losses in the code, I don't know what cause this issue.
Hope for your reply :)

**Comment by xhowdonewd** [comment]
I had the same problem, did you solve it

**Comment by ztrbq** [comment]
> I had the same problem, did you solve it

I haven't solved this problem but I decide to give it up, it stuck me for over a week. :-(

**Comment by dianzl** [comment]
Hello! The reason for this problem is that the gradient of the previous frames is used multiple times during the temporal information extraction process. We have modified the codes of this part, and now it can work. Thank you for your issue.

**Comment by ztrbq** [comment]
> Hello! The reason for this problem is that the gradient of the previous frames is used multiple times during the temporal information extraction process. We have modified the codes of this part, and now it can work. Thank you for your issue.

Thanks for your reply!
I've tried to run this code on PKU-SOD dataset on one single GPU and it works fine. Thanks again for your great work.

However, when I tried to run this code on multiple GPUs (like 2 3090 gpus), the code seems stuck before loading the data. The terminal clip is like this:
![image](https://github.com/dianzl/SODFormer/assets/45473111/425fded1-a92b-4849-a0ca-bc9ae7b31dde)
I checked the code but cannot find what causes this.

**Comment by Hatins** [comment]
@ztrbq  Hi, it seems that we are schoolmates and working on an event-based object detection, could I have you number for communication?

**Comment by ztrbq** [comment]
> @ztrbq Hi, it seems that we are schoolmates and working on an event-based object detection, could I have you number for communication?

sure, feel free to contact me at bingquanzhou@icloud.com.

**Comment by ztrbq** [comment]
> > Hello! The reason for this problem is that the gradient of the previous frames is used multiple times during the temporal information extraction process. We have modified the codes of this part, and now it can work. Thank you for your issue.
> 
> Thanks for your reply! I've tried to run this code on PKU-SOD dataset on one single GPU and it works fine. Thanks again for your great work.
> 
> However, when I tried to run this code on multiple GPUs (like 2 3090 gpus), the code seems stuck before loading the data. The terminal clip is like this: ![image](https://private-user-images.githubusercontent.com/45473111/289895687-425fded1-a92b-4849-a0ca-bc9ae7b31dde.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMjY0MDQsIm5iZiI6MTcwOTAyNjEwNCwicGF0aCI6Ii80NTQ3MzExMS8yODk4OTU2ODctNDI1ZmRlZDEtYTkyYi00ODQ5LWEwY2EtYmM5YWU3YjMxZGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA5MjgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YTI4MTY5OGFlNzc5ZTU5ZDljNDQ0NWU3YWNhZGRiZjI5MmFjYzEyZThkMTZiY2M5MjVkNmFjNTRiN2U0ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GoaIgyeiucW9bokj4ei_i8cH_CfwyL0-23xeeTlCsnI) I checked the code but cannot find what causes this.

btw, the code seems to work fine suddenly. I'll close this issue, thanks again for your great work.
